# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
create_index_hnsw <- function(dim, max_size) {
    .Call(`_vecstore_create_index_hnsw`, dim, max_size)
}

#' @export
validate_index_hnsw <- function(index) {
    invisible(.Call(`_vecstore_validate_index_hnsw`, index))
}

#' @export
add_item_hnsw <- function(ptr, data, label) {
    invisible(.Call(`_vecstore_add_item_hnsw`, ptr, data, label))
}

#' @export
find_hnsw <- function(ptr, q, k) {
    .Call(`_vecstore_find_hnsw`, ptr, q, k)
}

