# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Create an index for hierarchical navigable small worlds (HNSW) search
#'
#' This function initializes an empty index for HNSW search with a specified dimension.
#'
#' @param dim The dimension of the feature space.
#' @param max_size The dimension of the feature space.
#' @param M Parameter that defines the maximum number of outgoing connections in the graph.
#' @param ef_construction Parameter that controls speed/accuracy trade-off during the index construction.
#' @return A list containing an initialized index with an empty data matrix.
#' @export
#'
#' @examples
#' index <- create_index_hnsw(3, 16, 10, 200)
create_index_hnsw <- function(dim, max_size, M, ef_construction) {
    .Call(`_vecstore_create_index_hnsw`, dim, max_size, M, ef_construction)
}

#' Add a data point to the index
#'
#' This function appends a new data point to the existing kNN index.
#'
#' @param ptr The index to which the data will be added.
#' @param data A vector of length (\code{dim}) to be added to the index.
#' @param label The corresponding scalar label for the data point.
#' @return Returns `NULL`
#' @export
#'
#' @examples
#' index <- create_index_hnsw(3, 16, 10, 200)
#' add_hnsw(index, c(1, 2, 3), 1)
add_hnsw <- function(ptr, data, label) {
    invisible(.Call(`_vecstore_add_hnsw`, ptr, data, label))
}

#' Search for top K nearest neighbors
#'
#' This function finds the k nearest neighbors to a query vector within the index.
#'
#' @param ptr The index containing the data points.
#' @param q The query vector of length (\code{dim}) for which neighbors are to be found.
#' @param k The number of nearest neighbors to find.
#' @return Indices of the k nearest neighbors.
#' @export
#'
#' @examples
#' index <- create_index_hnsw(3, 16, 10, 200)
#' add_hnsw(index, c(1, 2, 3), 1)
#' I <- find_hnsw(index, c(2, 3, 4), k = 1)
find_hnsw <- function(ptr, q, k) {
    .Call(`_vecstore_find_hnsw`, ptr, q, k)
}

