# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Create an HNSW index
#'
#' This function initializes an empty index for HNSW search with a specified dimension and max size.
#'
#' @param dim The dimension of the feature space.
#' @param max_size The maximum capacity of the index
#' @return A list containing an initialized index with an empty data matrix.
NULL

#' Create an HNSW index
#'
#' This function initializes an empty index for HNSW search with a specified dimension and max size.
#'
#' @param dim The dimension of the feature space.
#' @param max_size The maximum capacity of the index
#' @return A list containing an initialized index with an empty data matrix.
#' @export
create_index_hnsw <- function(dim, max_size) {
    .Call(`_vecstore_create_index_hnsw`, dim, max_size)
}

